.PHONY: all welcome generate clean

all: welcome generate

welcome:
	@echo "Hello world..."
generate:
	@echo "Creating empty text files..."
	touch file-{1..10}.txt
clean:
	@echo "Cleaning up..."
	rm *.txt